version: '3.8'
services:
    node-service:
        image: node-service
        build: .
        container_name: node-service
        restart: always
        ports: 
            - 3333:3333
        command: npm start
